---
- hosts: server

  gather_facts: no

  vars_files:
    - secrets.yml

  pre_tasks:
    - name: Use default SSH port
      set_fact:
        ansible_port: "{{ default_ssh_port }}"

  tasks:
    - name: Install python
      raw: apt-get -y install python3 python3-pip python3-setuptools
