FROM debian

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y upgrade

RUN apt-get -y install \
        build-essential \
        python3 \
        python3-pip \
        python \
        python-pip
